import { useState, useRef, useEffect } from "react";
import {
  ArrowLeft, ChevronRight, Send, Sparkles, ToggleLeft, ToggleRight,
  Copy, Check, FileText, CheckCircle2,
} from "lucide-react";
import { cn } from "@/lib/utils";
import type { AppItem } from "./AppsTab";

// ─── Types ────────────────────────────────────────────────────────────────────

type FlowStep = 0 | 1 | 2 | "done";
type Tab = "ai" | "config" | "skill-file";

type Message =
  | { role: "ai"; text: string }
  | { role: "user"; text: string }
  | { role: "building"; text: string }
  | { role: "action"; type: "app-created"; appName: string; useCase: string };

interface GenericConfig {
  appName: string;
  useCase: string;
  targetAudience: string;
  language: string;
  autoEscalation: boolean;
  notifications: boolean;
  integrations: string;
  notes: string;
}

const EMPTY_CONFIG: GenericConfig = {
  appName: "",
  useCase: "",
  targetAudience: "",
  language: "English",
  autoEscalation: false,
  notifications: true,
  integrations: "",
  notes: "",
};

const LANGUAGE_OPTIONS = [
  "English", "Hindi", "Hinglish", "Bengali", "Tamil", "Telugu", "Marathi",
];

// ─── Skill file generator ─────────────────────────────────────────────────────

function generateSkillFile(config: GenericConfig, appName: string): string {
  const name = config.appName || appName;
  const lines = [
    `# ${name} — Skill File`,
    ``,
    `> Auto-generated by OMNI Forge`,
    ``,
    `---`,
    ``,
    `## Overview`,
    `**App:** ${name}`,
    `**Use Case:** ${config.useCase || "Not specified"}`,
    `**Target Audience:** ${config.targetAudience || "Not specified"}`,
    `**Language:** ${config.language}`,
    ``,
    `## Runtime Configuration`,
    `- Auto-escalation: ${config.autoEscalation ? "✓ Enabled" : "✗ Disabled"}`,
    `- Notifications: ${config.notifications ? "✓ Enabled" : "✗ Disabled"}`,
    `- Integrations: ${config.integrations || "None configured"}`,
    ``,
  ];
  if (config.notes) lines.push(`## Notes`, config.notes, ``);
  return lines.join("\n");
}

function isSkillReady(config: GenericConfig): boolean {
  return !!config.appName && !!config.useCase;
}

// ─── Guided-flow step responses ───────────────────────────────────────────────

function getStepResponse(completedStep: 0 | 1, config: GenericConfig): string {
  if (completedStep === 0) {
    return `Great name — **${config.appName}**!\n\nStep 2 of 3: What is the **primary goal or use case** for this app?\n\nExamples: Customer support, Lead qualification, After-sales service, Internal operations, Compliance tracking`;
  }
  return `Got it — **${config.useCase}**.\n\nStep 3 of 3: Who is the **target audience** or end user?\n\nExamples: New customers, Enterprise clients, Internal teams, Sales reps, Support agents`;
}

// ─── Markdown-lite renderer ───────────────────────────────────────────────────

function renderText(text: string) {
  return text.split("\n").map((line, li, arr) => {
    const parts = line.split(/\*\*(.+?)\*\*/g);
    return (
      <span key={li}>
        {parts.map((part, pi) =>
          pi % 2 === 1 ? (
            <strong key={pi} className="font-semibold text-[#0a0a0a]">{part}</strong>
          ) : part
        )}
        {li < arr.length - 1 && <br />}
      </span>
    );
  });
}

// ─── Reusable form sub-components ────────────────────────────────────────────

function SectionHeading({ title }: { title: string }) {
  return (
    <p className="mb-3 text-[11px] font-semibold uppercase tracking-widest text-[#a0a0a0]">{title}</p>
  );
}

function FieldWrap({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-1.5 rounded-lg border border-[#e7e7f0] bg-white px-3 py-2.5">
      <label className="text-[11px] font-semibold uppercase tracking-wider text-[#737373]">{label}</label>
      {children}
    </div>
  );
}

function ToggleRow({
  checked, onChange, label, description,
}: {
  checked: boolean;
  onChange: (v: boolean) => void;
  label: string;
  description?: string;
}) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-lg border border-[#e7e7f0] bg-white px-3 py-2.5">
      <div className="flex min-w-0 flex-col gap-0.5">
        <span className="text-sm font-medium text-[#0a0a0a]">{label}</span>
        {description && (
          <span className="text-[11px] leading-[1.3] text-[#a0a0a0]">{description}</span>
        )}
      </div>
      <button
        type="button"
        onClick={() => onChange(!checked)}
        role="switch"
        aria-checked={checked}
        className="shrink-0"
      >
        {checked
          ? <ToggleRight className="size-7 text-purple-600" strokeWidth={1.5} />
          : <ToggleLeft className="size-7 text-[#c0c0c0]" strokeWidth={1.5} />
        }
      </button>
    </div>
  );
}

const inputCls =
  "w-full bg-transparent text-sm text-[#0a0a0a] placeholder:text-[#c0c0c0] outline-none leading-5";
const selectCls =
  "w-full appearance-none bg-transparent text-sm text-[#0a0a0a] outline-none leading-5 cursor-pointer";

// ─── Main component ───────────────────────────────────────────────────────────

interface AppConfigPageProps {
  app: AppItem;
  onBack: () => void;
  onSave: () => void;
  isAlreadySaved?: boolean;
}

export default function AppConfigPage({
  app,
  onBack,
  onSave,
  isAlreadySaved = false,
}: AppConfigPageProps) {
  const [activeTab, setActiveTab] = useState<Tab>("ai");
  const [config, setConfig] = useState<GenericConfig>(EMPTY_CONFIG);
  const [flowStep, setFlowStep] = useState<FlowStep>(isAlreadySaved ? "done" : 0);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [copied, setCopied] = useState(false);
  const [isBuilding, setIsBuilding] = useState(false);

  const greetedRef = useRef(false);
  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Scroll to bottom whenever messages update
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isTyping]);

  // Initial greeting
  useEffect(() => {
    if (greetedRef.current) return;
    greetedRef.current = true;

    setIsTyping(true);
    const t = setTimeout(() => {
      const greeting = isAlreadySaved
        ? `Welcome back to **${app.name}**!\n\nDescribe what you'd like to change, or ask me anything about this app's configuration.`
        : `Hi! Let's get your **${app.name}** app set up — just **3 quick questions**.\n\nStep 1 of 3: **What would you like to name this app configuration?**\n\nExamples: "${app.name} — ACKO Drive", "Support Ops India", "Sales Acceleration 2026"`;
      setMessages([{ role: "ai", text: greeting }]);
      setIsTyping(false);
    }, 700);

    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function updateField<K extends keyof GenericConfig>(key: K, value: GenericConfig[K]) {
    setConfig((prev) => ({ ...prev, [key]: value }));
  }

  function handleSend() {
    const val = input.trim();
    if (!val || isTyping || isBuilding) return;

    setMessages((prev) => [...prev, { role: "user", text: val }]);
    setInput("");
    setIsTyping(true);

    if (flowStep === "done") {
      // Free-form chat in edit mode
      setTimeout(() => {
        setMessages((prev) => [
          ...prev,
          {
            role: "ai",
            text: `Noted! I've logged that for **${config.appName || app.name}**.\n\nYou can also update settings directly in the **Configuration** tab.`,
          },
        ]);
        setIsTyping(false);
        inputRef.current?.focus();
      }, 600 + Math.random() * 300);
      return;
    }

    const currentStep = flowStep as number;
    let updatedConfig = { ...config };

    if (currentStep === 0) {
      updatedConfig = { ...updatedConfig, appName: val };
    } else if (currentStep === 1) {
      updatedConfig = { ...updatedConfig, useCase: val };
    } else if (currentStep === 2) {
      updatedConfig = { ...updatedConfig, targetAudience: val };
    }

    setConfig(updatedConfig);
    const nextStep = currentStep + 1;

    setTimeout(() => {
      if (nextStep <= 2) {
        const response = getStepResponse(currentStep as 0 | 1, updatedConfig);
        setMessages((prev) => [...prev, { role: "ai", text: response }]);
        setFlowStep(nextStep as FlowStep);
        setIsTyping(false);
        inputRef.current?.focus();
      } else {
        // All 3 questions answered → building sequence
        const completionMsg = `All done — **${updatedConfig.targetAudience}**.\n\nSetting up your **${updatedConfig.appName || app.name}** app now…`;
        setMessages((prev) => [...prev, { role: "ai", text: completionMsg }]);

        const buildingSteps = [
          "Saving configuration...",
          `Provisioning **${updatedConfig.appName || app.name}** runtime...`,
          "Generating skill file...",
        ];

        setIsBuilding(true);
        buildingSteps.forEach((text, i) => {
          setTimeout(() => {
            setMessages((prev) => [...prev, { role: "building", text } as Message]);
          }, 400 + i * 600);
        });

        const totalDelay = 400 + (buildingSteps.length - 1) * 600 + 700;
        setTimeout(() => {
          setIsBuilding(false);
          setFlowStep("done");
          setMessages((prev) => [
            ...prev,
            {
              role: "action",
              type: "app-created",
              appName: updatedConfig.appName || app.name,
              useCase: updatedConfig.useCase,
            } as Message,
          ]);
          setIsTyping(false);
          onSave();
        }, totalDelay);
      }
    }, 600 + Math.random() * 200);
  }

  const TABS: { id: Tab; label: string }[] = [
    { id: "ai", label: "AI Assistant" },
    { id: "config", label: "Configuration" },
    { id: "skill-file", label: "Skill File" },
  ];

  const stepNum = flowStep === "done" ? 3 : (flowStep as number);
  const isGuided = flowStep !== "done";
  const skillFileContent = generateSkillFile(config, app.name);
  const skillReady = isSkillReady(config);

  return (
    <main className="flex flex-1 flex-col overflow-hidden bg-[#fafafa]">
      {/* Breadcrumb */}
      <div className="flex shrink-0 items-center gap-2.5 border-b border-[#e7e7f0] bg-white px-8 py-3.5">
        <button
          type="button"
          onClick={onBack}
          className="flex size-8 items-center justify-center rounded-md border border-[#e5e5e5] bg-white shadow-sm transition-colors hover:bg-[#f5f5f5]"
        >
          <ArrowLeft className="size-4 text-[#0a0a0a]" />
        </button>
        <button
          type="button"
          onClick={onBack}
          className="text-sm text-[#737373] transition-colors hover:text-[#0a0a0a]"
        >
          Apps
        </button>
        <ChevronRight className="size-3.5 text-[#a0a0a0]" />
        <span className="text-sm font-medium text-[#0a0a0a]">{app.name}</span>
        {isAlreadySaved && (
          <span className="ml-1 rounded-full bg-[#f0f0f0] px-2.5 py-0.5 text-[11px] font-medium text-[#737373]">
            Editing
          </span>
        )}
      </div>

      {/* Tab bar */}
      <div className="flex shrink-0 items-end border-b border-[#e7e7f0] bg-white px-8">
        {TABS.map((tab) => (
          <button
            key={tab.id}
            type="button"
            onClick={() => setActiveTab(tab.id)}
            className={cn(
              "relative flex h-10 items-center gap-1.5 px-4 text-sm transition-colors",
              activeTab === tab.id
                ? "font-semibold text-purple-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:rounded-full after:bg-purple-600"
                : "font-medium text-[#737373] hover:text-[#0a0a0a]"
            )}
          >
            {tab.id === "skill-file" && <FileText className="size-3.5 shrink-0" />}
            {tab.label}
          </button>
        ))}

        {/* Guided flow step indicator */}
        {isGuided && activeTab === "ai" && (
          <div className="ml-auto flex items-center gap-2 pb-1 pr-1">
            <span className="text-[11px] text-[#a0a0a0]">Step {stepNum + 1} of 3</span>
            <div className="flex gap-1">
              {[0, 1, 2].map((i) => (
                <span
                  key={i}
                  className={cn(
                    "h-1.5 rounded-full transition-all",
                    i <= stepNum ? "w-4 bg-purple-500" : "w-1.5 bg-[#e0e0e0]"
                  )}
                />
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Tab content area */}
      <div className="flex-1 overflow-hidden">

        {/* ══ Tab 1: AI Assistant ══ */}
        {activeTab === "ai" && (
          <div className="flex h-full flex-col">
            <div className="flex-1 overflow-y-auto px-8 py-6">
              <div className="flex max-w-[680px] flex-col gap-3">
                {messages.map((msg, i) => {
                  if (msg.role === "building") {
                    return (
                      <div key={i} className="flex items-center gap-2.5 animate-fade-in py-0.5">
                        <Check className="size-3.5 shrink-0 text-green-500" strokeWidth={2.5} />
                        <span className="text-[13px] text-[#737373]">{renderText(msg.text)}</span>
                      </div>
                    );
                  }

                  if (msg.role === "action" && msg.type === "app-created") {
                    return (
                      <div key={i} className="self-start w-full max-w-[88%] animate-fade-in">
                        <div className="mb-0.5 flex items-center gap-1.5">
                          <div className="flex size-5 items-center justify-center rounded-full bg-purple-600">
                            <Sparkles className="size-2.5 text-white" />
                          </div>
                          <span className="text-[11px] font-medium text-[#737373]">OMNI Forge</span>
                        </div>
                        <div className="overflow-hidden rounded-2xl rounded-tl-sm border border-green-200 bg-white shadow-sm">
                          <div className="flex items-center gap-3 bg-gradient-to-r from-green-500 to-emerald-500 px-4 py-3.5">
                            <div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-white/20">
                              <CheckCircle2 className="size-5 text-white" strokeWidth={2} />
                            </div>
                            <div>
                              <p className="text-[13px] font-bold text-white">App is live!</p>
                              <p className="text-[11px] text-white/80">
                                {msg.appName} is active and ready to use
                              </p>
                            </div>
                          </div>
                          <div className="px-4 py-4">
                            <p className="text-[17px] font-bold text-[#0a0a0a]">{msg.appName}</p>
                            {msg.useCase && (
                              <div className="mt-2 flex flex-wrap gap-2">
                                <span className="rounded-full bg-purple-50 px-2.5 py-1 text-[11px] font-medium text-purple-700">
                                  🎯 {msg.useCase}
                                </span>
                              </div>
                            )}
                            <div className="mt-4 flex gap-2">
                              <button
                                type="button"
                                onClick={() => setActiveTab("config")}
                                className="flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-[#e5e5e5] bg-white px-3 py-2.5 text-[13px] font-medium text-[#0a0a0a] transition-colors hover:bg-[#f5f5f5]"
                              >
                                Configuration
                              </button>
                              <button
                                type="button"
                                onClick={() => setActiveTab("skill-file")}
                                className="flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-[#e5e5e5] bg-white px-3 py-2.5 text-[13px] font-medium text-[#0a0a0a] transition-colors hover:bg-[#f5f5f5]"
                              >
                                <FileText className="size-3.5 shrink-0" strokeWidth={1.5} />
                                Skill File
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    );
                  }

                  return (
                    <div
                      key={i}
                      className={cn(
                        "flex max-w-[88%] flex-col gap-1 animate-fade-in",
                        msg.role === "user" ? "self-end items-end" : "self-start items-start"
                      )}
                    >
                      {msg.role === "ai" && (
                        <div className="mb-0.5 flex items-center gap-1.5">
                          <div className="flex size-5 items-center justify-center rounded-full bg-purple-600">
                            <Sparkles className="size-2.5 text-white" />
                          </div>
                          <span className="text-[11px] font-medium text-[#737373]">OMNI Forge</span>
                        </div>
                      )}
                      <div
                        className={cn(
                          "rounded-2xl px-3.5 py-2.5 text-sm leading-[1.55]",
                          msg.role === "ai"
                            ? "rounded-tl-sm border border-[#e5e5e5] bg-white text-[#0a0a0a]"
                            : "rounded-tr-sm bg-purple-600 text-white"
                        )}
                      >
                        {renderText(msg.text)}
                      </div>
                    </div>
                  );
                })}

                {isTyping && (
                  <div className="flex max-w-[88%] flex-col gap-1 self-start items-start animate-fade-in">
                    <div className="mb-0.5 flex items-center gap-1.5">
                      <div className="flex size-5 items-center justify-center rounded-full bg-purple-600">
                        <Sparkles className="size-2.5 text-white" />
                      </div>
                      <span className="text-[11px] font-medium text-[#737373]">OMNI Forge</span>
                    </div>
                    <div className="flex items-center gap-1 rounded-2xl rounded-tl-sm border border-[#e5e5e5] bg-white px-4 py-3">
                      {[0, 1, 2].map((i) => (
                        <span
                          key={i}
                          className="h-1.5 w-1.5 rounded-full bg-[#d4d4d4]"
                          style={{ animation: `dotBounce 1.2s ease-in-out ${i * 0.2}s infinite` }}
                        />
                      ))}
                    </div>
                  </div>
                )}

                <div ref={bottomRef} />
              </div>
            </div>

            {/* Chat input */}
            <div className="shrink-0 border-t border-[#e7e7f0] bg-white px-8 py-4">
              <div className="flex max-w-[680px] items-center gap-3 rounded-xl border border-[#e7e7f0] bg-[#fafafa] px-4 py-2.5">
                <input
                  ref={inputRef}
                  type="text"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                      e.preventDefault();
                      handleSend();
                    }
                  }}
                  disabled={isTyping || isBuilding}
                  placeholder={
                    isBuilding
                      ? "Setting up your app…"
                      : flowStep === "done"
                      ? "Ask a question or describe a change…"
                      : "Type your answer…"
                  }
                  className="flex-1 bg-transparent text-sm text-[#0a0a0a] placeholder:text-[#a0a0a0] outline-none leading-5 disabled:opacity-40"
                  autoFocus
                />
                <button
                  type="button"
                  onClick={handleSend}
                  disabled={!input.trim() || isTyping || isBuilding}
                  className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-purple-600 text-white transition-colors hover:bg-purple-700 disabled:cursor-not-allowed disabled:opacity-40"
                >
                  <Send className="size-3.5" />
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ══ Tab 2: Configuration ══ */}
        {activeTab === "config" && (
          <div className="h-full overflow-y-auto px-8 py-6">
            <div className="mx-auto max-w-[880px]">
              <div className="grid grid-cols-2 gap-x-8 gap-y-6">

                {/* App Details */}
                <div className="col-span-2">
                  <SectionHeading title="App Details" />
                  <div className="grid grid-cols-2 gap-3">
                    <FieldWrap label="App name">
                      <input
                        type="text"
                        value={config.appName}
                        onChange={(e) => updateField("appName", e.target.value)}
                        placeholder={`e.g. ${app.name} — ACKO Drive`}
                        className={inputCls}
                      />
                    </FieldWrap>
                    <FieldWrap label="Use case / Goal">
                      <input
                        type="text"
                        value={config.useCase}
                        onChange={(e) => updateField("useCase", e.target.value)}
                        placeholder="e.g. Customer support, Lead qualification"
                        className={inputCls}
                      />
                    </FieldWrap>
                    <FieldWrap label="Target audience">
                      <input
                        type="text"
                        value={config.targetAudience}
                        onChange={(e) => updateField("targetAudience", e.target.value)}
                        placeholder="e.g. New customers, Enterprise clients"
                        className={inputCls}
                      />
                    </FieldWrap>
                    <FieldWrap label="Language">
                      <select
                        value={config.language}
                        onChange={(e) => updateField("language", e.target.value)}
                        className={selectCls}
                      >
                        {LANGUAGE_OPTIONS.map((o) => (
                          <option key={o} value={o}>{o}</option>
                        ))}
                      </select>
                    </FieldWrap>
                    <FieldWrap label="Integrations">
                      <input
                        type="text"
                        value={config.integrations}
                        onChange={(e) => updateField("integrations", e.target.value)}
                        placeholder="e.g. Salesforce, Zendesk, Slack"
                        className={inputCls}
                      />
                    </FieldWrap>
                    <FieldWrap label="Additional notes">
                      <textarea
                        value={config.notes}
                        onChange={(e) => updateField("notes", e.target.value)}
                        placeholder="Any special instructions or context…"
                        rows={2}
                        className={cn(inputCls, "resize-none")}
                      />
                    </FieldWrap>
                  </div>
                </div>

                {/* Runtime Settings */}
                <div className="col-span-2">
                  <SectionHeading title="Runtime Settings" />
                  <div className="grid grid-cols-2 gap-3">
                    <ToggleRow
                      checked={config.autoEscalation}
                      onChange={(v) => updateField("autoEscalation", v)}
                      label="Auto-escalation"
                      description="Automatically route complex issues to human agents"
                    />
                    <ToggleRow
                      checked={config.notifications}
                      onChange={(v) => updateField("notifications", v)}
                      label="Notifications"
                      description="Send alerts for critical events and status changes"
                    />
                  </div>
                </div>
              </div>
              <div className="h-8" />
            </div>
          </div>
        )}

        {/* ══ Tab 3: Skill File ══ */}
        {activeTab === "skill-file" && (
          <div className="h-full overflow-y-auto px-8 py-6">
            <div className="mx-auto max-w-[720px]">
              <div className="mb-4 flex items-start justify-between gap-4">
                <div>
                  <h2 className="text-[15px] font-semibold text-[#0a0a0a]">Skill File</h2>
                  <p className="mt-0.5 text-[12px] text-[#737373]">
                    Auto-generated from your configuration. Powers everything this app produces.
                  </p>
                </div>
                {skillReady && (
                  <button
                    type="button"
                    onClick={() => {
                      navigator.clipboard.writeText(skillFileContent).then(() => {
                        setCopied(true);
                        setTimeout(() => setCopied(false), 2000);
                      });
                    }}
                    className="flex shrink-0 items-center gap-1.5 rounded-lg border border-[#e5e5e5] bg-white px-3 py-2 text-[12px] font-medium text-[#0a0a0a] shadow-sm transition-colors hover:bg-[#f5f5f5]"
                  >
                    {copied ? <Check className="size-3.5 text-green-600" /> : <Copy className="size-3.5" />}
                    {copied ? "Copied!" : "Copy"}
                  </button>
                )}
              </div>

              {skillReady ? (
                <div className="overflow-hidden rounded-xl border border-[#e7e7f0] bg-[#0e0e0e]">
                  <div className="flex items-center gap-2 border-b border-white/10 px-4 py-3">
                    <div className="flex gap-1.5">
                      <span className="size-3 rounded-full bg-[#ff5f57]" />
                      <span className="size-3 rounded-full bg-[#ffbd2e]" />
                      <span className="size-3 rounded-full bg-[#28c840]" />
                    </div>
                    <span className="ml-2 text-[11px] text-white/40">
                      {(config.appName || app.name).toLowerCase().replace(/\s+/g, "-")}.skill.md
                    </span>
                  </div>
                  <pre className="overflow-x-auto whitespace-pre-wrap break-words px-5 py-5 font-mono text-[13px] leading-[1.7] text-white/80">
                    {skillFileContent}
                  </pre>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center gap-3 rounded-xl border border-dashed border-[#e7e7f0] bg-white py-20 text-center">
                  <div className="flex size-12 items-center justify-center rounded-xl bg-[#f5f5f5]">
                    <FileText className="size-5 text-[#a0a0a0]" />
                  </div>
                  <p className="text-sm font-medium text-[#0a0a0a]">No skill file yet</p>
                  <p className="max-w-[280px] text-[12px] leading-[1.5] text-[#737373]">
                    Complete the AI assistant setup or fill in the App name and Use case in the Configuration tab to generate your skill file.
                  </p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
